# Site
# repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Hannah YoungEun An
title: URCS graduate student
email: yan2@ur.rochester.edu
website: hannah0n.github.io

# Social links
twitter_username: hannah0n
github_username:  hannah0n
linkedin_username: hannah-an

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a second-year PhD student at the University of Rochester in [Computer Science](https://www.cs.rochester.edu/). My research is in Natural Language Understanding and/or Computatinal Linguistics, with a focus on building ontologies and mining commonsense knowledge. Specifically, I work on building commonsense knowledge with a deep semantic lexicon and automating inference rule extraction with [James Allen](http://www.cs.rochester.edu/~james/), and organizing world knowledge into schemas to reflect the relational understanding between entities as well as between knowledge and action with [Len Schubert](https://www.cs.rochester.edu/~schubert/).

  In the past, I was involved in [FACTS.lab](http://factslab.io/)'s [MegaAttitude Project](http://megaattitude.io/) for building lexicon-scale datasets from crowdsourcing and studying the semantic contribution of lexical items and syntactic structures.

#  For CS400 fake proposal reviews: *[proposal](https://docs.google.com/gview?url=https://github.com/hannah0n/temp-400/raw/master/proposal.pdf).*

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

papers_title: Papers

teaching_title: Teaching

# Education Section
education_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#    - Rock climbing
#    - Gaming
#    - Knitting
#    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
